vich_uploader:
    db_driver: orm

    mappings:
        cvs:
            uri_prefix: /files/cvs
            upload_destination: '%kernel.project_dir%/public/files/cvs'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true